name: kacityguide
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  esense_flutter: any
  flutter_blue: any
  shared_preferences: any
  yaml: ^2.2.1
  flutter_sound_lite: any
  flutter_map: any
  sqflite: any
  path: any
  synchronized: any
  flutter_local_notifications: ^1.4.4+2
  workmanager: ^0.2.3
  geolocator: ^6.1.14
  background_locator: ^1.4.0
  location_permissions: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/locations/
    - assets/locations/schloss/
    - assets/locations/hebeldenkmal/
    - assets/locations/ehrenhof/
    - assets/locations/bundesverfassungsgericht/
    - assets/locations/pyramide/
    - assets/locations/gottesau/
    - assets/locations/staatstheater/
    - assets/locations/gerwigbrunnen/
    - assets/map/
    - assets/map/12/2143/
    - assets/map/13/4286/
    - assets/map/13/4287/
    - assets/map/14/8572/
    - assets/map/14/8573/
    - assets/map/14/8574/
    - assets/map/14/8575/
    - assets/map/15/17145/
    - assets/map/15/17146/
    - assets/map/15/17147/
    - assets/map/15/17148/
    - assets/map/15/17149/
    - assets/map/15/17150/
    - assets/map/15/17151/
    - assets/map/16/34290/
    - assets/map/16/34291/
    - assets/map/16/34292/
    - assets/map/16/34293/
    - assets/map/16/34294/
    - assets/map/16/34295/
    - assets/map/16/34296/
    - assets/map/16/34297/
    - assets/map/16/34298/
    - assets/map/16/34299/
    - assets/map/16/34300/
    - assets/map/16/34301/
    - assets/map/16/34302/
    - assets/map/16/34303/
    - assets/map/17/68581/
    - assets/map/17/68582/
    - assets/map/17/68583/
    - assets/map/17/68584/
    - assets/map/17/68585/
    - assets/map/17/68586/
    - assets/map/17/68587/
    - assets/map/17/68588/
    - assets/map/17/68589/
    - assets/map/17/68590/
    - assets/map/17/68591/
    - assets/map/17/68592/
    - assets/map/17/68593/
    - assets/map/17/68594/
    - assets/map/17/68595/
    - assets/map/17/68596/
    - assets/map/17/68597/
    - assets/map/17/68598/
    - assets/map/17/68599/
    - assets/map/17/68600/
    - assets/map/17/68601/
    - assets/map/17/68602/
    - assets/map/17/68603/
    - assets/map/17/68604/
    - assets/map/17/68605/
    - assets/map/17/68606/
    - assets/map/17/68607/
    - assets/map/18/137163/
    - assets/map/18/137164/
    - assets/map/18/137165/
    - assets/map/18/137166/
    - assets/map/18/137167/
    - assets/map/18/137168/
    - assets/map/18/137169/
    - assets/map/18/137170/
    - assets/map/18/137171/
    - assets/map/18/137172/
    - assets/map/18/137173/
    - assets/map/18/137174/
    - assets/map/18/137175/
    - assets/map/18/137176/
    - assets/map/18/137177/
    - assets/map/18/137178/
    - assets/map/18/137179/
    - assets/map/18/137180/
    - assets/map/18/137181/
    - assets/map/18/137182/
    - assets/map/18/137183/
    - assets/map/18/137184/
    - assets/map/18/137185/
    - assets/map/18/137186/
    - assets/map/18/137187/
    - assets/map/18/137188/
    - assets/map/18/137189/
    - assets/map/18/137190/
    - assets/map/18/137191/
    - assets/map/18/137192/
    - assets/map/18/137193/
    - assets/map/18/137194/
    - assets/map/18/137195/
    - assets/map/18/137196/
    - assets/map/18/137197/
    - assets/map/18/137198/
    - assets/map/18/137199/
    - assets/map/18/137200/
    - assets/map/18/137201/
    - assets/map/18/137202/
    - assets/map/18/137203/
    - assets/map/18/137204/
    - assets/map/18/137205/
    - assets/map/18/137206/
    - assets/map/18/137207/
    - assets/map/18/137208/
    - assets/map/18/137209/
    - assets/map/18/137210/
    - assets/map/18/137211/
    - assets/map/18/137212/
    - assets/map/18/137213/
    - assets/map/18/137214/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
